
A throw statement exits from a method and so on and so on or it is caught by a try/catch block. It does not return a variable but an exception: